version: '3.6'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 1111:80
    volumes:
      - ./:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
  php:
    build:
      context: .
    restart: always
    volumes:
      - ./:/var/www/html
      - ./conf/php.conf:/etc/php/7.2/pool.d/www.conf
    dns:
      - 8.8.8.8
    networks:
      - default
networks:
  default_network:
    name: default
    driver: bridge